### ISSUE TITLE
Getting angulaj digest cycle errors with groupSort: true

### ISSUE THREAD

**Issue by bronzovik** [obogo/ux-angularjs-datagrid#84] opened 2015-10-27 21:13 UTC
Hi, I'm getting the following with grid 1.3.2 & angular 1.4.7

```
TypeError: Cannot read property '$$nextSibling' of null
    at Scope.$digest (angular.js:15854)
    at Scope.$apply (angular.js:16097)
    at angular.js:17864
    at completeOutstandingRequest (angular.js:5507)
    at angular.js:5784
```

The error is not constant. Sometimes it works. Sometimes toggleSort should be called twice. I can make a repo with the example I'm using if required.

p.s. https://github.com/bronzovik/grid-sort-example

**Comment by wesjones** [comment] 2015-11-11 23:57
This should be fixed with 1.4.1.

Thanks.

**Comment by bronzovik** [comment] 2015-11-12 21:06
Still having the same issue with 1.4.2

**Comment by wesjones** [comment] 2015-11-13 17:24
Update to 1.4.3.
The grid flow and the $digest from angular were not always in sync and this caused a conflict.
The grid is now respectful of a digest being in progress and will render after.

However, one part that is seen here is that in your project you are missing this part of the css so it makes the rows show their "{{code}}" briefly before it completes. Adding this css which should be default for the datagrid will make those rows not show until they are done. However, you can change the fade out of this css if you don't want them to fade.

```
.datagrid-row > * {
   -webkit-transition: opacity 0.5s ease-out;
   -moz-transition: opacity 0.5s ease-out;
   -ms-transition: opacity 0.5s ease-out;
   -o-transition: opacity 0.5s ease-out;
   transition: opacity 0.5s ease-out;
}

.uncompiled > * {
   visibility: hidden;
   opacity: 0;
}

.compiled > * {
   opacity: 1;
}

.datagrid-chunk {
   opacity: 0;
   -webkit-transition: opacity 0.5s ease-out;
   -moz-transition: opacity 0.5s ease-out;
   -ms-transition: opacity 0.5s ease-out;
   -o-transition: opacity 0.5s ease-out;
   transition: opacity 0.5s ease-out;
}

.datagrid-chunk-ready {
   opacity: 1;
}
```

**Comment by bronzovik** [comment] 2015-11-13 20:44
Hi Wes,
it looks like 1.4.3 has fixed it. Thanks a lot and thank you for the heads up with the CSS!
Still gotta check variable row height feature.

**Comment by wesjones** [comment] 2015-11-13 20:51
Awesome! Your git example for me to work with was SO helpful because I had seen the error before, but was not sure how to reproduce it, Thanks for your help!

**Closed** 2015-11-13 20:51 UTC
Labels: bug
